'use client';

import type { Split } from '@/lib/types';
import { Avatar } from '@/components/ui/Avatar';
import { getUserAvatarUrl } from '@/lib/orderParticipants';
import { isSplitClosed } from '@/lib/splitStatus';
import { formatCurrency, getRelativeTime, cn } from '@/lib/utils';
import { useWebHaptics } from 'web-haptics/react';
import { usePrefetchOnIntent } from '@/hooks/usePrefetch';
import {
  entityListCardClassName,
  EntityCardDivider,
  EntityCardFooter,
  EntityMetaItem,
  EntityCardTitle,
  EntityCardAsideTotal,
  EntityStatusPill,
  EntityCardActionIcon,
} from '@/components/ui/EntityListCard';
import { Icon } from '@/components/ui/Icon';

interface SplitCardProps {
  split: Split;
  total: number;
  canEdit?: boolean;
  canDelete?: boolean;
  onOpen: () => void;
  /** Rota do detalhe — pré-carregada no primeiro toque/hover. */
  href?: string;
  onEdit?: (e: React.MouseEvent) => void;
  onDelete?: (e: React.MouseEvent) => void;
  className?: string;
  style?: React.CSSProperties;
}

function isAutoGeneratedSplit(split: Split): boolean {
  return Boolean(split.description?.includes('Gerado automaticamente'));
}

function displayTitle(name: string): string {
  return name.replace(/^Divisão:\s*/i, '').trim() || name;
}

export function SplitCard({
  split,
  total,
  canEdit = false,
  canDelete = false,
  onOpen,
  href,
  onEdit,
  onDelete,
  className,
  style,
}: SplitCardProps) {
  const { trigger } = useWebHaptics();
  const prefetch = usePrefetchOnIntent(href);
  const creator = split.expand?.created_by;
  const creatorName = creator?.name?.trim() || 'Membro';
  const itemCount = split.items?.length || 0;
  const participantCount = split.participants?.length || 0;
  const showDescription =
    Boolean(split.description?.trim()) && !isAutoGeneratedSplit(split);
  const closed = isSplitClosed(split);

  const adminActions = (
    <>
      {canEdit && onEdit && (
        <EntityCardActionIcon
          title="Editar divisão"
          className="hover:text-primary-600 dark:hover:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/20"
          onActivate={(e) => onEdit(e as React.MouseEvent)}
        >
          <Icon name="edit" className="text-[22px]" />
        </EntityCardActionIcon>
      )}
      {canDelete && onDelete && (
        <EntityCardActionIcon
          title="Eliminar divisão"
          hapticError
          className="hover:text-red-500 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20"
          onActivate={(e) => onDelete(e as React.MouseEvent)}
        >
          <Icon name="delete_outline" className="text-[22px]" />
        </EntityCardActionIcon>
      )}
    </>
  );

  return (
    <button
      type="button"
      {...prefetch}
      onClick={() => {
        trigger();
        onOpen();
      }}
      className={cn(entityListCardClassName, className)}
      style={style}
    >
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <EntityCardTitle>{displayTitle(split.name)}</EntityCardTitle>
          {creator && (
            <div className="flex items-center gap-2 mt-2 min-w-0">
              <Avatar
                name={creatorName}
                src={getUserAvatarUrl(creator.id, creator.avatar)}
                size="sm"
              />
              <span className="text-sm text-[var(--text-secondary)] truncate">
                {creatorName}
              </span>
            </div>
          )}
          {showDescription && (
            <p className="text-sm text-[var(--text-muted)] line-clamp-2 mt-2">
              {split.description}
            </p>
          )}
        </div>
        <EntityCardAsideTotal value={formatCurrency(total)} />
      </div>

      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <EntityMetaItem icon="receipt_long">
          {itemCount} {itemCount === 1 ? 'item' : 'itens'}
        </EntityMetaItem>
        {participantCount > 0 && (
          <EntityMetaItem icon="groups">
            {participantCount}{' '}
            {participantCount === 1 ? 'pessoa' : 'pessoas'}
          </EntityMetaItem>
        )}
        <EntityMetaItem icon="schedule">
          {getRelativeTime(split.created)}
        </EntityMetaItem>
      </div>

      <EntityCardDivider />

      <EntityCardFooter
        left={
          <>
            {closed ? (
              <EntityStatusPill variant="closed">Fechada</EntityStatusPill>
            ) : (
              <EntityStatusPill variant="open">Aberta</EntityStatusPill>
            )}
          </>
        }
        right={adminActions}
      />
    </button>
  );
}
